# Generated by Django 2.2.3 on 2019-12-03 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Manager_Console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityChosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member_Console.FacilityChosen')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager_Console.Facility')),
            ],
        ),
        migrations.AddField(
            model_name='facilitychosen',
            name='choice',
            field=models.ManyToManyField(through='Member_Console.Membership', to='Manager_Console.Facility'),
        ),
        migrations.AddField(
            model_name='facilitychosen',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('description', models.TextField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
